// <auto-generated />
using BoxLoader.Repository.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoxLoader.Repository.Migrations
{
    [DbContext(typeof(BoxLoaderDbContext))]
    [Migration("20240219181112_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BoxLoader.Repository.Models.Boxes.Box", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SupplierIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identifier");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("BoxLoader.Repository.Models.Boxes.Content", b =>
                {
                    b.Property<string>("PoNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BoxIdentifier")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("PoNumber");

                    b.HasIndex("BoxIdentifier");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("BoxLoader.Repository.Models.Boxes.Content", b =>
                {
                    b.HasOne("BoxLoader.Repository.Models.Boxes.Box", "Box")
                        .WithMany("Contents")
                        .HasForeignKey("BoxIdentifier");

                    b.Navigation("Box");
                });

            modelBuilder.Entity("BoxLoader.Repository.Models.Boxes.Box", b =>
                {
                    b.Navigation("Contents");
                });
#pragma warning restore 612, 618
        }
    }
}
